---
- name: Installing maven module
  hosts: u
  remote_user: ubuntu
  become_user: root
  become: yes
  tasks:
  - name: update OS
    shell: apt-get update
  - name: java version
    shell: java -version
    register: java_version
  - debug: 
      var: java_version
  - name: Download maven 
    get_url: url="https://dlcdn.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz" dest="/home/ubuntu/"
  - name: Extract maven
    shell: env -C /home/ubuntu tar -zvxf apache-maven-3.8.7-bin.tar.gz
  - name: checking maven.sh file
    stat:
      path: /etc/profile.d/maven.sh
    register: mvn
  - name: create maven.sh file
    file: path=/etc/profile.d/maven.sh state=touch
    when: not mvn.stat.exists
  - name: setting-up environment variables
    lineinfile: 
      path: /home/ubuntu/.bashrc
      line: "{{ item }}"
    with_items:
    - 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.18.0.10-2.el9_1.x86_64'
    - 'export M2_HOME=/home/ubuntu/apache-maven-3.8.7-bin'
    - 'export MAVEN_HOME=/home/ubuntu/apache-maven-3.8.7-bin'
    - 'export PATH=${M2_HOME}/bin:${PATH}'

  - name: source file
    shell: |
    source /home/ubuntu/.bashrc

  - name: verify installation
    shell: "mvn -version | grep -w 'Apache Maven' | awk '{print $3}'"
    register: mvn_version

  - debug:
     var: mvn_version