---
- name: frome control server
  hosts: u
  remote_user: ubuntu
  become_user: root
  tasks:
  - name: creating multiple files with 654 perm
    file: path="{{item}}" state=touch mode=654
    with_items:
    - '/home/ubuntu/1.txt'
    - '/home/ubuntu/2.txt'
