---
- name: sample playbook
  hosts: u
  remote_user: ubuntu
  become: true
  tasks:
  - name: install httpd
    apt:
        name: apache2
        state: latest
  - name: run httpd
    service: 
            name: apache2
            state: started
  - name: create content
    copy:
         content: "Congrats on installing ansible"
         dest: /var/www/html/index.html
