---
- hosts: u
  remote_user: ubuntu
  become: yes
  tasks:
  - name: copying from nexus
    get_url:
      url: http://52.66.222.90:8081/repository/Javawebapp-snapshot/com/maven/SimpleWebApplication/1.0.2-SNAPSHOT/SimpleWebApplication-1.0.2-20230208.075803-1.war
      dest: /home/ubuntu/backup
      username: admin
      password: admin123